### ISSUE TITLE
Using minitest-line programmatically

### ISSUE THREAD

**Issue by alain-andre** [judofyr/minitest-line#19]
Hi there,

I'm trying to programmatically run files at a specific line for my guard. I have created a [stackoverflow](https://stackoverflow.com/questions/48587874/guardminitest-programmatically-run-a-file-at-specific-line) question and I'm wondering if you could help me.

**Comment by grosser** [comment]
using `ruby #{file}:#{line}` would work for you ?
... if it does then adding support for multiple lines might work too ...
or do you want to run the tests in the same process ? (spring-like)

**Comment by alain-andre** [comment]
Hi @grosser, I'm in a class inside my guardfile.

What I need is when guard catch a modification, that it select the modified lines of the changed file and start the test at this lines.

My Guardfile is like this 

```ruby
class GitModifiedMatcher
  class MatchData
    def initialize(result)
      @result = result
    end

    def to_a
      @result.values
    end

    def [](name)
      @result[name]
    end
  end

  def match(filename_or_pathname)
    diff = `git diff --no-ext-diff --unified=0 --exit-code -a --no-prefix #{filename_or_pathname}`
    modified_lines = diff.to_enum(:scan, /^@@ -\d+,?.* [+](\d+),?.* @@.*/).map { Regexp.last_match(1) }

    return nil if modified_lines.count.zero?
    #Minitest::Test.tests_with_lines
    MatchData.new(file: filename_or_pathname)
  end
end

guard :minitest, all_on_start: false do
  watch(GitModifiedMatcher.new)
end
```

Instead of using Matchdata (`MatchData.new(file: filename_or_pathname)`), I would like to run a test for every lines in `modified_lines` on `filename_or_pathname`

**Comment by grosser** [comment]
if there was only a single line, then would running `ruby #{file} -l
#{line}` work or do you need to run the test directly inside the current
process ?

If yes, then it should be possible to modify minitest-line to accept
multiple lines.

**Comment by alain-andre** [comment]
@grosser I need to run it in current process. I changed my code this way : 

```ruby
class GitModifiedMatcher
  def match(file)
    diff = `git diff --no-ext-diff --unified=0 --exit-code -a --no-prefix #{file}`
    modified_lines = diff.to_enum(:scan, /^@@ -\d+,?.* [+](\d+),?.* @@.*/).map { Regexp.last_match(1) }

    modified_lines.each do |line|
      puts "Running #{file} at line #{line}"
      `ruby #{file} -l #{line}`
    end
  end
end
```

It fails because it does not find `test_helper` and then start to launch the whole tests of the file:

```ruby
Running test/api/v01/plannings_test.rb at line 131
test/api/v01/plannings_test.rb:1:in `require': cannot load such file -- test_helper (LoadError)
	from test/api/v01/plannings_test.rb:1:in `<main>'
10:18:19 - INFO - Running: test/api/v01/plannings_test.rb
```
